#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : cfitsio
Version  : 1
Release  : 1
URL      : http://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/cfitsio3450.tar.gz
Source0  : http://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/cfitsio3450.tar.gz
Summary  : A library of C and Fortran subroutines for reading and writing data files in FITS (Flexible Image Transport System) data format
Group    : Development/Tools
License  : ISC
Requires: cfitsio-lib = %{version}-%{release}
Requires: cfitsio-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : curl-dev

%description
CFITSIO Interface Library
CFITSIO is a library of ANSI C routines for reading and writing FITS
format data files.  A set of Fortran-callable wrapper routines are also
gives a brief summary of how to build and test CFITSIO, but the CFITSIO
User's Guide, found in the files cfitsio.doc (plain text), cfitsio.tex
(LaTeX source file), cfitsio.ps, or cfitsio.pdf should be
referenced for the latest and most complete information.

%package dev
Summary: dev components for the cfitsio package.
Group: Development
Requires: cfitsio-lib = %{version}-%{release}
Provides: cfitsio-devel = %{version}-%{release}

%description dev
dev components for the cfitsio package.


%package lib
Summary: lib components for the cfitsio package.
Group: Libraries
Requires: cfitsio-license = %{version}-%{release}

%description lib
lib components for the cfitsio package.


%package license
Summary: license components for the cfitsio package.
Group: Default

%description license
license components for the cfitsio package.


%prep
%setup -q -n cfitsio

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1548116187
mkdir -p clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1548116187
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/cfitsio
cp License.txt %{buildroot}/usr/share/package-licenses/cfitsio/License.txt
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libcfitsio.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libcfitsio.so.3
/usr/lib64/libcfitsio.so.3.45

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/cfitsio/License.txt
